import math
import torch
import warnings
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.checkpoint as checkpoint
from functools import reduce, lru_cache
from operator import mul
from einops import rearrange
from einops.layers.torch import Rearrange

def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0], ) + (1, ) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output

class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            'mean is more than 2 std from [a, b] in nn.init.trunc_normal_. '
            'The distribution of values may be incorrect.',
            stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        low = norm_cdf((a - mean) / std)
        up = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [low, up], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * low - 1, 2 * up - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution.

    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py

    The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value

    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def get_window_size(x_size, window_size, shift_size=None):
    """ Get the window size and the shift size """

    use_window_size = list(window_size)
    if shift_size is not None:
        use_shift_size = list(shift_size)
    for i in range(len(x_size)):
        if x_size[i] <= window_size[i]:
            use_window_size[i] = x_size[i]
            if shift_size is not None:
                use_shift_size[i] = 0

    if shift_size is None:
        return tuple(use_window_size)
    else:
        return tuple(use_window_size), tuple(use_shift_size)
    
def window_partition(x, window_size):
    """ Partition the input into windows. Attention will be conducted within the windows.

    Args:
        x: (B, D, H, W, C)
        window_size (tuple[int]): window size

    Returns:
        windows: (B*num_windows, window_size*window_size, C)
    """
    B, D, H, W, C = x.shape
    x = x.view(B, D // window_size[0], window_size[0], H // window_size[1], window_size[1], W // window_size[2],
               window_size[2], C)
    windows = x.permute(0, 1, 3, 5, 2, 4, 6, 7).contiguous().view(-1, reduce(mul, window_size), C)

    return windows

def window_reverse(windows, window_size, B, D, H, W):
    """ Reverse windows back to the original input. Attention was conducted within the windows.

    Args:
        windows: (B*num_windows, window_size, C)
        window_size (tuple[int]): Window size
        H (int): Height of image
        W (int): Width of image

    Returns:
        x: (B, D, H, W, C)
    """
    x = windows.view(B, D // window_size[0], H // window_size[1], W // window_size[2], window_size[0], window_size[1],
                     window_size[2], -1)
    x = x.permute(0, 1, 4, 2, 5, 3, 6, 7).contiguous().view(B, D, H, W, -1)

    return x

@lru_cache()
def compute_mask(D, H, W, window_size, shift_size, device):
    """Compute attnetion mask for input of size (D, H, W). @lru_cache caches each stage results."""
    img_mask = torch.zeros((1, D, H, W, 1), device=device)
    d_slices = (slice(-window_size[0]),
                slice(-window_size[0], -shift_size[0]),
                slice(-shift_size[0], None))
    h_slices = (slice(-window_size[1]),
                slice(-window_size[1], -shift_size[1]),
                slice(-shift_size[1], None))
    w_slices = (slice(-window_size[2]),
                slice(-window_size[2], -shift_size[2]),
                slice(-shift_size[2], None))
    cnt = 0
    for d in d_slices:
        for h in h_slices:
            for w in w_slices:
                img_mask[:, d, h, w, :] = cnt
                cnt += 1
    mask_windows = window_partition(img_mask, window_size) # [nW, ws[0]*ws[1]*ws[2], 1]
    mask_windows = mask_windows.squeeze(-1) # [nW, ws[0]*ws[1]*ws[2]]
    attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2) # [nW, 1, ws[0]*ws[1]*ws[2]] - [nW, ws[0]*ws[1]*ws[2], 1]
    attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))
    
    return attn_mask # [nW, ws[0]*ws[1]*ws[2], ws[0]*ws[1]*ws[2]]
    
    
## Gated-Dconv Feed-Forward Network (GDFN)
class Gated_Dconv_FeedForward(nn.Module):
    def __init__(self,
                 dim,
                 bias=False,
                 ffn_expansion_factor=2.66,
                 norm_layer=nn.LayerNorm,
                 act_layer=nn.GELU
                 ):
        super().__init__()
        self.norm = norm_layer(dim)
        
        hidden_features = int(ffn_expansion_factor*dim)
        
        self.project_in = nn.Conv3d(dim, hidden_features*2, kernel_size=1, bias=bias)
        self.dwconv = nn.Conv3d(hidden_features*2, hidden_features*2, kernel_size=(1, 3, 3), padding=(0, 1, 1), groups=hidden_features*2, bias=bias)
        self.act_fn = act_layer()
        self.project_out = nn.Conv3d(hidden_features, dim, kernel_size=1, bias=bias)
        self.fc = nn.Linear(dim, dim)
        
    def forward(self, x):
        """
        Args:
            x: [B, F, H, W, C]
        Returns:
            x: [B, F, H, W, C]
        """
        x = self.norm(x)
        x = rearrange(x, 'B F H W C -> B C F H W')
        x = self.dwconv(self.project_in(x))
        x1, x2 = torch.chunk(x, 2, dim=1)
        x = self.act_fn(x1) * x2
        x = self.project_out(x)
        x = rearrange(x, 'B C F H W -> B F H W C')
        x = self.fc(x)
        return x


## Downsample
class Downsample(nn.Module):
    def __init__(self, num_feat):
        super().__init__()
        
        self.down1 = nn.Conv3d(num_feat, num_feat // 2, kernel_size=(1, 3, 3), padding=(0, 1, 1), bias=False)
        self.down2 = nn.PixelUnshuffle(2)
        
    def forward(self, x):
        """
        Args:
            x: [B C F H W]
        Return:
            x: [B 2*C F H/2 W/2]
        """
        B, _, F, _, _ = x.shape
        x = self.down1(x)   # x: [B C F H W] -> x: [B C/2 F H W]
        x = rearrange(x, 'B C F H W -> (B F) C H W')  # x: [B C/2 F H W] -> x: [B*F C/2 H W]
        x = self.down2(x)   # x: [B*F C/2 H W] -> x: [B*F 2C H/2 W/2]
        x = rearrange(x, '(B F) C H W -> B C F H W', B=B, F=F)
        return x
        

## Upsample
class Upsample(nn.Module):
    def __init__(self, num_feat):
        super().__init__()
        
        self.up1 = nn.Conv3d(num_feat, num_feat * 2, kernel_size=(1, 3, 3), padding=(0, 1, 1), bias=False)
        self.up2 = nn.PixelShuffle(2)
        
    def forward(self, x):
        """
        Args:
            x: [B C F H W]
        Return:
            x: [B C/2 F H*2 W*2]
        """
        B, _, F, _, _ = x.shape
        x = self.up1(x)
        x = rearrange(x, 'B C F H W -> (B F) C H W')
        x = self.up2(x)
        x = rearrange(x, '(B F) C H W -> B C F H W', B=B, F=F)
        return x


## Overlapped Patch Embedding with Conv3d
class OverlapPatchEmbed(nn.Module):
    def __init__(self, in_ch=16, embed_dim=96):
        super().__init__()
        self.proj = nn.Conv3d(in_ch, embed_dim, kernel_size=(1, 3, 3), padding=(0, 1, 1), bias=False)

    def forward(self, x):
        x = self.proj(x)
        return x


## Shifted Window Attention
class WindowAttention(nn.Module):
    
    def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None, cross_attn=True):
        super().__init__()
        
        self.window_size = window_size
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5
        self.cross_attn = cross_attn
        
        self.qkv_spec = nn.Linear(dim, dim*3, bias=qkv_bias)
        self.qkv_spatem = nn.Linear(dim, dim*3, bias=qkv_bias)
        self.softmax = nn.Softmax(dim=-1)
        self.proj = nn.Linear(dim*2, dim)
        
        # Spectral self attention with relative position bias
        self.relative_position_bias_table = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1) * (2 * window_size[2] - 1),
                        num_heads))  # 2*Wd-1 * 2*Wh-1 * 2*Ww-1, nH
        self.register_buffer("relative_position_index", self.get_position_index(window_size))
        trunc_normal_(self.relative_position_bias_table, std=.02)
        
        # Spatio-Temporal cross attention with sine position encoding
        if self.cross_attn:
            self.register_buffer("position_bias",
                                 self.get_sine_position_encoding(window_size[1:], dim // 2, normalize=True))
        
    def get_position_index(self, window_size):
        ''' Get pair-wise relative position index for each token inside the window. '''

        coords_d = torch.arange(window_size[0])
        coords_h = torch.arange(window_size[1])
        coords_w = torch.arange(window_size[2])
        coords = torch.stack(torch.meshgrid(coords_d, coords_h, coords_w, indexing='ij'))  # 3, Wd, Wh, Ww
        coords_flatten = torch.flatten(coords, 1)  # 3, Wd*Wh*Ww
        relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # 3, Wd*Wh*Ww, Wd*Wh*Ww
        relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # Wd*Wh*Ww, Wd*Wh*Ww, 3
        relative_coords[:, :, 0] += window_size[0] - 1  # shift to start from 0
        relative_coords[:, :, 1] += window_size[1] - 1
        relative_coords[:, :, 2] += window_size[2] - 1

        relative_coords[:, :, 0] *= (2 * window_size[1] - 1) * (2 * window_size[2] - 1)
        relative_coords[:, :, 1] *= (2 * window_size[2] - 1)
        relative_position_index = relative_coords.sum(-1)  # Wd*Wh*Ww, Wd*Wh*Ww

        return relative_position_index
    
    def get_sine_position_encoding(self, HW, num_pos_feats=64, temperature=10000, normalize=False, scale=None):
        """ Get sine position encoding """

        if scale is not None and normalize is False:
            raise ValueError("normalize should be True if scale is passed")

        if scale is None:
            scale = 2 * math.pi

        not_mask = torch.ones([1, HW[0], HW[1]])
        y_embed = not_mask.cumsum(1, dtype=torch.float32)
        x_embed = not_mask.cumsum(2, dtype=torch.float32)
        if normalize:
            eps = 1e-6
            y_embed = y_embed / (y_embed[:, -1:, :] + eps) * scale
            x_embed = x_embed / (x_embed[:, :, -1:] + eps) * scale

        dim_t = torch.arange(num_pos_feats, dtype=torch.float32)
        dim_t = temperature ** (2 * (dim_t // 2) / num_pos_feats)

        # BxCxHxW
        pos_x = x_embed[:, :, :, None] / dim_t
        pos_y = y_embed[:, :, :, None] / dim_t
        pos_x = torch.stack((pos_x[:, :, :, 0::2].sin(), pos_x[:, :, :, 1::2].cos()), dim=4).flatten(3)
        pos_y = torch.stack((pos_y[:, :, :, 0::2].sin(), pos_y[:, :, :, 1::2].cos()), dim=4).flatten(3)
        pos_embed = torch.cat((pos_y, pos_x), dim=3).permute(0, 3, 1, 2)

        return pos_embed.flatten(2).permute(0, 2, 1).contiguous()
    
    # Spectral Self Attention
    def spectral_branch(self, q, k, v, x_shape):
        B_, N, C = x_shape
        attn = (q * self.scale) @ k.transpose(-2, -1).contiguous()         # [B_, nH, C//nH, C//nH]
        attn = self.softmax(attn)
        out = (attn @ v).transpose(1, 3).contiguous().reshape(B_, N, C) # [B_, nH, C//nH, N] -> [B_, N, C//nH, nH] -> [B_, N, C]
        return out
    
    # Spatio-Temporal Self/Cross Attention
    def spatio_temporal_branch(self, q, k, v, mask, x_shape, relative_position_encoding=True):
        B_, N, C = x_shape
        attn = (q * self.scale) @ k.transpose(-2, -1).contiguous()         # [B_, nH, N, N] or [B_, nH, N/2, N/2]
        
        if relative_position_encoding:
            relative_position_bias = self.relative_position_bias_table[
                self.relative_position_index[:N, :N].reshape(-1)].reshape(N, N, -1)  # Wd*Wh*Ww, Wd*Wh*Ww,nH
            attn = attn + relative_position_bias.permute(2, 0, 1).unsqueeze(0)  # B_, nH, N, N
            
        if mask is None:
            attn = self.softmax(attn)
        else:
            nW = mask.shape[0]
            attn = attn.view(B_ // nW, nW, self.num_heads, N, N).contiguous() + mask[:, :N, :N].unsqueeze(1).unsqueeze(0) # [B_ // nW, nW, nH, N, N]
            attn = attn.view(-1, self.num_heads, N, N).contiguous() # [B_, nH, N, N]
            attn = self.softmax(attn)
            
        out = (attn @ v).transpose(1, 2).contiguous().reshape(B_, N, C)  # [B_, nH, N, C // nH] -> [B_, N, nH, C // nH] -> [B_, N, C]
        return out
    
    def forward(self, x, mask=None):
        """ Forward function.

        Args:
            x: input features with shape of (num_windows*B, N, C)
            mask: (0/-inf) mask with shape of (num_windows, N, N) or None
        """
        B_, N, C = x.shape
        
        # Spectral Branch (self attention)
        qkv_spec = self.qkv_spec(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4) # [3, B_, nH, N, C // nH]
        q_spec, k_spec, v_spec = qkv_spec[0], qkv_spec[1], qkv_spec[2] # [B_, nH, N, C // nH]
        
        q_spec = rearrange(q_spec, 'B head N C_nH -> B head C_nH N')
        k_spec = rearrange(k_spec, 'B head N C_nH -> B head C_nH N')
        v_spec = rearrange(v_spec, 'B head N C_nH -> B head C_nH N')
        out_spec = self.spectral_branch(q_spec, k_spec, v_spec, (B_, N, C))
        
        # Spatio-Temporal Branch (2 frames cross attention or 5 frames self attention)
        if self.cross_attn:
            qkv_spatem = x + self.position_bias.repeat(1, 2, 1)
            qkv_spatem = self.qkv_spatem(qkv_spatem).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4) # [3, B_, nH, N, C // nH]
            q_spatem, k_spatem, v_spatem = qkv_spatem[0], qkv_spatem[1], qkv_spatem[2] # [B_, nH, N, C // nH]
            
            (q1, q2) = torch.chunk(q_spatem, 2, dim=2)
            (k1, k2) = torch.chunk(k_spatem, 2, dim=2)
            (v1, v2) = torch.chunk(v_spatem, 2, dim=2)
            
            out1_aligned = self.spatio_temporal_branch(q1, k2, v2, mask, (B_, N//2, C), relative_position_encoding=False)
            out2_aligned = self.spatio_temporal_branch(q2, k1, v1, mask, (B_, N//2, C), relative_position_encoding=False)
            out_spatem = torch.cat([out1_aligned, out2_aligned], dim=1)
        else:
            qkv_spatem = self.qkv_spatem(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4) # [3, B_, nH, N, C // nH]
            q_spatem, k_spatem, v_spatem = qkv_spatem[0], qkv_spatem[1], qkv_spatem[2] # [B_, nH, N, C // nH]
            
            out_spatem = self.spatio_temporal_branch(q_spatem, k_spatem, v_spatem, mask, (B_, N, C), relative_position_encoding=True)
            
        out = self.proj(torch.cat([out_spatem, out_spec], dim=2))
        
        return out


## S-T-S Prior Learning Transformer Block
class STSPLT_Block(nn.Module):
    def __init__(self,
                 dim,
                 num_heads,
                 window_size=[6, 8, 8],
                 shift_size=None,
                 cross_attn=True,
                 ffn_expand=2.66,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path=0.,
                 act_layer=nn.GELU,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False
                 ):
        super().__init__()
        
        self.window_size = window_size
        self.shift_size = shift_size
        self.use_checkpoint_attn = use_checkpoint_attn
        self.use_checkpoint_ffn = use_checkpoint_ffn
        
        assert 0 <= self.shift_size[0] < self.window_size[0], "shift_size must in 0-window_size"
        assert 0 <= self.shift_size[1] < self.window_size[1], "shift_size must in 0-window_size"
        assert 0 <= self.shift_size[2] < self.window_size[2], "shift_size must in 0-window_size"
        
        self.norm1 = norm_layer(dim)
        self.attn = WindowAttention(dim=dim, window_size=window_size, num_heads=num_heads, qkv_bias=qkv_bias,
                                    qk_scale=qk_scale, cross_attn=cross_attn)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        self.ffn = Gated_Dconv_FeedForward(dim=dim, ffn_expansion_factor=ffn_expand, act_layer=act_layer)
        
    def forward_part1(self, x, mask_matrix):
        B, D, H, W, C = x.shape
        window_size, shift_size = get_window_size((D, H, W), self.window_size, self.shift_size)
        
        x = self.norm1(x)
        
        # pad feature maps to multiples of window size
        pad_l = pad_t = pad_d0 = 0
        pad_d1 = (window_size[0] - D % window_size[0]) % window_size[0]
        pad_b = (window_size[1] - H % window_size[1]) % window_size[1]
        pad_r = (window_size[2] - W % window_size[2]) % window_size[2]
        x = F.pad(x, (0, 0, pad_l, pad_r, pad_t, pad_b, pad_d0, pad_d1), mode='constant')
        
        _, Dp, Hp, Wp, _ = x.shape
        # cycle shift
        if any(i > 0 for i in shift_size):
            shifted_x = torch.roll(x, shifts=(-shift_size[0], -shift_size[1], -shift_size[2]), dims=(1, 2, 3))
            attn_mask = mask_matrix
        else:
            shifted_x = x
            attn_mask = None
            
        # partition windows
        x_windows = window_partition(shifted_x, window_size) # B*nW, Wd*Wh*Ww, C
        
        # attention / shifted attention
        attn_windows = self.attn(x_windows, attn_mask) # B*nW, Wd*Wh*Ww, C
        
        # merge windows
        attn_windows = attn_windows.view(-1, *(window_size + (C,))) # B*nW, Wd, Wh, Ww, C
        shifted_x = window_reverse(attn_windows, window_size, B, Dp, Hp, Wp) # B D' H' W' C
        
        # reverse cyclic shift
        if any(i > 0 for i in shift_size):
            x = torch.roll(shifted_x, shifts=(shift_size[0], shift_size[1], shift_size[2]), dims=(1, 2, 3))
        else:
            x = shifted_x
        
        if pad_d1 > 0 or pad_r > 0 or pad_b > 0:
            x = x[:, :D, :H, :W, :]
            
        x = self.drop_path(x)
        
        return x
    
    def forward_part2(self, x):
        return self.drop_path(self.ffn(self.norm2(x)))
         
    def forward(self, x, mask_matrix):
        """
        Args:
            x: [B F H W C]
            mask_matrix: Attention mask for cyclic shift.
        Return:
        
        """
        if self.use_checkpoint_attn:
            x = x + checkpoint.checkpoint(self.forward_part1, x, mask_matrix, use_reentrant=False)
        else:
            x = x + self.forward_part1(x, mask_matrix)
            
        # feed-forward
        if self.use_checkpoint_ffn:
            x = x + checkpoint.checkpoint(self.forward_part2, x, use_reentrant=False)
        else:
            x = x + self.forward_part2(x)
            
        return x


class ResidualGroup(nn.Module):
    def __init__(self,
                 dim,
                 depth,
                 num_heads,
                 window_size=[6, 8, 8],
                 shift_size=None,
                 cross_attn=True,
                 ffn_expand=2.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path=0.,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False
                 ):
        super().__init__()
        
        self.window_size = window_size
        self.shift_size = list(i // 2 for i in window_size) if shift_size is None else shift_size
        
        # build blocks
        self.blocks = nn.ModuleList([
            STSPLT_Block(
                dim=dim,
                num_heads=num_heads,
                window_size=window_size,
                shift_size=[0, 0, 0] if i % 2 == 0 else self.shift_size,
                cross_attn=cross_attn,
                ffn_expand=ffn_expand,
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop_path=drop_path[i] if isinstance(drop_path, list) else drop_path,
                norm_layer=norm_layer,
                use_checkpoint_attn=use_checkpoint_attn,
                use_checkpoint_ffn=use_checkpoint_ffn
            ) for i in range(depth)
        ])

    def forward(self, x):
        """
        Args:
            x: [B C F H W]
        Return:
            x: [B C F H W]
        """
        # calculate attention mask for attention
        B, C, F, H, W = x.shape
        window_size, shift_size = get_window_size((F, H, W), self.window_size, self.shift_size)
        x = rearrange(x, 'B C F H W -> B F H W C')
        Fp = int(np.ceil(F / window_size[0])) * window_size[0]
        Hp = int(np.ceil(H / window_size[1])) * window_size[1]
        Wp = int(np.ceil(W / window_size[2])) * window_size[2]
        attn_mask = compute_mask(Fp, Hp, Wp, window_size, shift_size, x.device)
        
        for blk in self.blocks:
            x = blk(x, attn_mask)
            
        x = x.view(B, F, H, W, -1)
        x = rearrange(x, 'B F H W C -> B C F H W')
        
        return x
    

class Level(nn.Module):
    def __init__(self,
                 dim,
                 depth,
                 num_heads,
                 window_size,
                 cross_attn_ratio=0.5,
                 ffn_expand=2.0,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path=0.,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False
                 ):
        super().__init__()
        
        self.norm = nn.Sequential(Rearrange('B C F H W -> B F H W C'),
                                  nn.LayerNorm(dim),
                                  Rearrange('B F H W C -> B C F H W'))
        
        self.residual_group1 = ResidualGroup(dim=dim,
                                           depth=int(depth * cross_attn_ratio),
                                           num_heads=num_heads,
                                           window_size=[2, window_size[1], window_size[2]],
                                           cross_attn=True,
                                           ffn_expand=ffn_expand,
                                           qkv_bias=qkv_bias,
                                           qk_scale=qk_scale,
                                           drop_path=drop_path,
                                           norm_layer=norm_layer,
                                           use_checkpoint_attn=use_checkpoint_attn,
                                           use_checkpoint_ffn=use_checkpoint_ffn)
        self.linear1 = nn.Linear(dim, dim)
        
        self.residual_group2 = ResidualGroup(dim=dim,
                                           depth=depth - int(depth * cross_attn_ratio),
                                           num_heads=num_heads,
                                           window_size=window_size,
                                           cross_attn=False,
                                           ffn_expand=ffn_expand,
                                           qkv_bias=qkv_bias,
                                           qk_scale=qk_scale,
                                           drop_path=drop_path,
                                           norm_layer=norm_layer,
                                           use_checkpoint_attn=use_checkpoint_attn,
                                           use_checkpoint_ffn=use_checkpoint_ffn)
        self.linear2 = nn.Linear(dim, dim)
        
    def forward(self, x):
        """
        Args:
            x: [B C F H W]
        """
        x = self.norm(x)
        x = self.linear1(self.residual_group1(x).transpose(1, 4)).transpose(1, 4) + x
        x = self.linear2(self.residual_group2(x).transpose(1, 4)).transpose(1, 4) + x
        
        return x


## S-T-S Prior Learning Transformer
class STSPLT(nn.Module):
    def __init__(self,
                 in_ch=16,
                 out_ch=16,
                 embed_dim=96,
                 depths=[4, 4, 4],
                 num_heads=[3, 3, 3],
                 window_size=[5, 8, 8],
                 NLE=True,
                 MLP_Cps=True,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path_rate=0.2,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=True,
                 use_checkpoint_ffn=True,
                 no_checkpoint_attn_blocks=[],
                 no_checkpoint_ffn_blocks=[],
                 ):
        super().__init__()
        self.nle = NLE
        self.mlp_cps = MLP_Cps
        
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]  # stochastic depth decay rule
        use_checkpoint_attns = [False if i in no_checkpoint_attn_blocks else use_checkpoint_attn for i in
                                range(len(depths))]
        use_checkpoint_ffns = [False if i in no_checkpoint_ffn_blocks else use_checkpoint_ffn for i in
                               range(len(depths))]
        
        # Conv_first
        if NLE:
            self.conv_first = nn.Sequential(Rearrange('B F C H W -> B C F H W'),
                                            nn.Conv3d(in_channels=32, out_channels=16,
                                                      kernel_size=(1, 3, 3), padding=(0, 1, 1)),
                                            Rearrange('B C F H W -> B F C H W'))
        
        # Overlapped patch embedding
        self.patch_embed = OverlapPatchEmbed(in_ch=in_ch, embed_dim=embed_dim)
        
        # Level 1
        self.downsample0_1 = Downsample(embed_dim)
        self.level1 = Level(
            dim=embed_dim * 2,
            depth=depths[0],
            num_heads=num_heads[0],
            window_size=window_size,
            cross_attn_ratio=2/3,
            ffn_expand=2.66,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            drop_path=dpr[0:3],
            norm_layer=norm_layer,
            use_checkpoint_attn=use_checkpoint_attns[0],
            use_checkpoint_ffn=use_checkpoint_ffns[0]
        )
        
        # Level 2
        self.downsample1_2 = Downsample(embed_dim * 2)
        self.level2 = Level(
            dim=embed_dim * 4,
            depth=depths[1],
            num_heads=num_heads[1],
            window_size=window_size,
            cross_attn_ratio=2/3,
            ffn_expand=2.66,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            drop_path=dpr[3:6],
            norm_layer=norm_layer,
            use_checkpoint_attn=use_checkpoint_attns[1],
            use_checkpoint_ffn=use_checkpoint_ffns[1]
        )
        
        # Level 3
        self.upsample2_3 = Upsample(embed_dim * 4)
        self.reduce_level3 = nn.Conv3d(embed_dim * 4 * 2, embed_dim * 4, kernel_size=(1, 1, 1), bias=False)
        self.level3 = Level(
            dim=embed_dim * 2,
            depth=depths[2],
            num_heads=num_heads[2],
            window_size=window_size,
            cross_attn_ratio=2/3,
            ffn_expand=2.66,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            drop_path=dpr[6:9],
            norm_layer=norm_layer,
            use_checkpoint_attn=use_checkpoint_attns[2],
            use_checkpoint_ffn=use_checkpoint_ffns[2]
        )
        
        # Reconstruction Module
        self.upsample_recon = Upsample(embed_dim * 2)
        self.reduce_recon = nn.Conv3d(embed_dim * 2 * 2, embed_dim * 2, kernel_size=(1, 1, 1), bias=False)
        self.recon = nn.Sequential(
            nn.Conv3d(embed_dim, embed_dim // 4, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
            nn.LeakyReLU(negative_slope=0.2, inplace=True),
            nn.Conv3d(embed_dim // 4, embed_dim // 4, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
            nn.LeakyReLU(negative_slope=0.2, inplace=True),
            nn.Conv3d(embed_dim // 4, out_ch, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
        )
        
        
    def forward(self, x, n):
        """
        Args:
            x: [B, F, C, H, W]  ==  [B, 5, 16, 256, 256]
            n: [B, F, C, H, W]  ==  [B, 5, 16, 256, 256]
        Return:
            x: [B, F, C, H, W]
        """
        
        # Conv first
        if self.nle:
            x = self.conv_first(torch.cat([x, n], dim=2))
        
        inp_level0 = x.clone()
        
        # Patch embedding
        out_level0 = self.patch_embed(x.transpose(1, 2).contiguous())        # out_level0: [B, C, F, H, W]
        
        # Level 1
        inp_level1 = self.downsample0_1(out_level0)             # inp_level1: [B, 2*C, F, H/2, W/2]
        out_level1 = self.level1(inp_level1)                    # out_level1: [B, 2*C, F, H/2, W/2]
        
        # Level 2
        inp_level2 = self.downsample1_2(out_level1)             # inp_level2: [B, 4*C, F, H/4, W/4]
        out_level2 = self.level2(inp_level2)                    # out_level2: [B, 4*C, F, H/4, W/4]
        
        # Level 3
        inp_level3 = torch.cat([out_level2, inp_level2], dim=1) # inp_level3: [B, 8*C, F, H/4, W/4]
        inp_level3 = self.reduce_level3(inp_level3)             # inp_level3: [B, 4*C, F, H/4, W/4]
        inp_level3 = self.upsample2_3(inp_level3)               # inp_level3: [B, 2*C, F, H/2, W/2]
        out_level3 = self.level3(inp_level3)                    # out_level3: [B, 2*C, F, H/2, W/2]
        
        # Reconstruction
        inp_recon = torch.cat([out_level3, inp_level1], dim=1)  # inp_recon: [B, 4*C, F, H/2, W/2]
        inp_recon = self.reduce_recon(inp_recon)                # inp_recon: [B, 2*C, F, H/2, W/2]
        inp_recon = self.upsample_recon(inp_recon)              # inp_recon: [B, C, F, H, W]
        out_recon = self.recon(inp_recon)                       # out_recon: [B, out_ch, F, H, W]
        out_recon = rearrange(out_recon, 'B C F H W -> B F C H W')
        
        if self.mlp_cps:
            out1 = out_recon[:, :, :-1, :, :] + inp_level0
            out2 = out_recon[:, :, -1, :, :]
            return out1, out2
        else:
            out = out_recon + inp_level0
            return out


# -----> Compressive Spectral Video Sensing Unfolding Framework <-----

def vectorize(inputs, choice):
    r""" Vectorize measurement y and tensor z
        (Column-major order)
    
    Args:
        inputs: y: [F H W] -> [5 256 286] if choice == 'y'
               z: [F C H W] -> [5 16 256 256] if choice == 'z'

    return:
        y_vec: [5*256*286,]
        z_vec: [5*16*256*256,]
    """
    if choice == 'y':
        y_t = inputs.transpose(1, 2).contiguous()
        y_vec = y_t.contiguous().view(-1)
        return y_vec
    elif choice == 'z':
        z_t = inputs.transpose(2, 3).contiguous()
        z_vec = z_t.contiguous().view(-1)
        return z_vec


def de_vectorize(inputs, shape):
    r""" return the matrix form of a vector
        (Column-major order)
    
    Args:
        inputs: [B F*C*H*W]
        
    return:
        outputs: [B F C H W]
    """
    B, F, C, H, W = shape
    out_mat = torch.reshape(inputs, (B, F, C, W, H))
    outputs = torch.transpose(out_mat, 3, 4)
    return outputs


## MLP Compensation
class MLP_cps(nn.Module):
    def __init__(self, in_chans, hidden_chans, out_chans, drop=0.3):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Conv3d(in_chans, hidden_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
            nn.ReLU(inplace=True),
            nn.Conv3d(hidden_chans, hidden_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
            nn.ReLU(inplace=True),
            nn.Conv3d(hidden_chans, out_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1))
        )
        
        
    def forward(self, x):
        """
        Input: x [B F H W]
        Return: x [B F*C*H*W]
        """
        x = x.unsqueeze(2) # x [B F 1 H W]
        x = rearrange(x, 'B F C H W -> B C F H W')
        x = self.mlp(x)
        x = rearrange(x, 'B C F H W -> B (F C H W)')
        return x


## Noise Level Estimator
class NLE(nn.Module):
    def __init__(self, in_chans=16, hidden_chans=32, out_chans=16):
        super().__init__()
        self.pwconv = nn.Conv3d(in_chans, hidden_chans, kernel_size=1, bias=True)
        self.dwconv = nn.Conv3d(hidden_chans, hidden_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1), groups=hidden_chans, bias=True)
        self.relu = nn.ReLU(inplace=True)
        self.avg_pool2d = nn.AdaptiveAvgPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(hidden_chans, hidden_chans, kernel_size=1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(hidden_chans, hidden_chans, kernel_size=1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(hidden_chans, out_chans, kernel_size=1, padding=0, bias=True),
            nn.Softplus()
        )
        
    def forward(self, x):
        """
        Args:
            x: [B F C H W]
        Return:
            x: [B F C H W]
        """
        B, F, _, _, _ = x.shape
        x = rearrange(x, 'B F C H W -> B C F H W').contiguous()
        x = self.dwconv(self.pwconv(x))
        x = self.relu(x)
        x = rearrange(x, 'B C F H W -> (B F) C H W')
        x = self.mlp(self.avg_pool2d(x))                           # [(B F) C 1 1]
        x = rearrange(x, '(B F) C H W -> B F C H W', B=B, F=F)
        return x


class zNet(nn.Module):
    def __init__(self, in_chans=17, out_chans=16, channel=32):
        super().__init__()
        self.fusion = nn.Sequential(
            nn.Conv3d(in_chans, channel, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
            nn.ReLU(inplace=True),
            nn.Conv3d(channel, channel, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
            nn.ReLU(inplace=True),
            nn.Conv3d(channel, out_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1))
        )
    
    def forward(self, x):
        """
        Inputs: [B 5 17 256 286]
        """
        x = rearrange(x, 'B F C H W -> B C F H W')
        x = self.fusion(x)
        x = rearrange(x, 'B C F H W -> B F C H W')
        return x[:, :, :, :256, :256]


## CSVSUF
class CSVSUF(nn.Module):
    ''' Main part of CSVSUF '''
    def __init__(self, opt):
        super().__init__()
        self.opt = opt
        self.num_iter = opt['num_iter']
        self.fution = zNet(in_chans=17, out_chans=16)
        
        # Gaussian Denoiser
        self.denoisers = nn.ModuleList([])
        for _ in range(opt['num_iter']):
            self.denoisers.append(
                STSPLT(
                    in_ch=opt['in_ch'],
                    out_ch=opt['out_ch'] if opt['MLP_Cps'] else 16,
                    embed_dim=opt['embed_dim'],
                    depths=opt['depths'],
                    num_heads=opt['num_heads'],
                    window_size=opt['window_size'],
                    NLE=opt['ANE'],
                    MLP_Cps=opt['MLP_Cps'],
                    qkv_bias=opt['qkv_bias'],
                    qk_scale=None,
                    drop_path_rate=opt['drop_path_rate'],
                    norm_layer=nn.LayerNorm,
                    use_checkpoint_attn=opt['use_checkpoint_attn'],
                    use_checkpoint_ffn=opt['use_checkpoint_ffn'],
                    no_checkpoint_attn_blocks=opt['no_checkpoint_attn_blocks'],
                    no_checkpoint_ffn_blocks=opt['no_checkpoint_ffn_blocks']
                )
            )
        
        # Compensation
        if opt['MLP_Cps']:
            self.mlp_cps = nn.ModuleList([])
            for _ in range(opt['num_iter'] - 1):
                self.mlp_cps.append(
                    MLP_cps(in_chans=1, hidden_chans=32, out_chans=16)
                )
        
        # Adaptive Noise Estimator
        if opt['ANE']:
            self.nle = nn.ModuleList([])
            for _ in range(opt['num_iter']):
                self.nle.append(
                    NLE(in_chans=16, hidden_chans=32, out_chans=16)
                )
                
    def z_init(self, y, masks_batch):
        [B, F, C, H, W] = masks_batch.shape
        masks_shift = torch.zeros(B, F, C, H, W + 2 * (C - 1)).cuda().float()
        for i in range(C):
            masks_shift[:, :, i, :, (i * 2):(i * 2 + W)] = masks_batch[:, :, i, :, :] # [B 5 16 256 286]
        y = y.unsqueeze(2)
        z = torch.cat([y, masks_shift], dim=2)
        z = self.fution(z)
        return z
    
    def forward(self, y, masks_batch, H_mtx, A_mtx):
        r"""
        Args:
            Inputs  y: [B F H W] -> [B 5 256 286]
                    masks_batch: [B F C H W]
                    H: [H*(W+step*(C-1))*F, F*C*H*W]
                    A: [F*C*H*W, H*(W+step*(C-1))*F]
            Output z: [B F C H W]
        """
        # Initialization
        B, F, C, H, W = masks_batch.shape
        # z = torch.zeros(B, F, C, H, W).cuda()
        z = self.z_init(y, masks_batch)
        x_temp = torch.zeros(B, F*C*H*W).cuda()
        c = torch.zeros(B, F*C*H*W).cuda()
        
        # Start iterating
        for i in range(self.num_iter):
            # X-update
            for j in range(B):
                temp_Hz = torch.mv(H_mtx, vectorize(z[j, :, :, :, :], choice='z'))
                temp_vec = vectorize(y[j, :, :, :], choice='y') - temp_Hz
                x_temp[j, :] = vectorize(z[j, :, :, :, :], choice='z') + torch.mv(A_mtx, temp_vec)
            
            if self.opt['MLP_Cps']:
                x = x_temp + c
            else:
                x = x_temp

            x = de_vectorize(x, shape=(B, F, C, H, W)) # x: [B F C H W]
            
            # Adaptive Noise Estimator
            if self.opt['ANE']:
                n = self.nle[i](x)              # n: [B F C 1 1]
                n = n.repeat(1, 1, 1, x.shape[3], x.shape[4])
            else:
                n = None
            
            ## Z-update
            if self.opt['MLP_Cps']:
                z, c = self.denoisers[i](x, n)
                if i < self.num_iter - 1:
                    c = self.mlp_cps[i](c)
            else:
                z = self.denoisers[i](x, n)

        return z

        